CREATE TYPE "public"."inlet_config_activity_kind" AS ENUM('publish', 'rollback', 'unpublish');--> statement-breakpoint
CREATE TYPE "public"."inlet_config_reach_kind" AS ENUM('fetch', 'not_modified', 'version', 'refused', 'condition', 'variant');--> statement-breakpoint
ALTER TYPE "public"."inlet_delivery_kind" ADD VALUE 'config_published';--> statement-breakpoint
ALTER TYPE "public"."inlet_delivery_kind" ADD VALUE 'config_rolled_back';--> statement-breakpoint
ALTER TYPE "public"."inlet_delivery_kind" ADD VALUE 'config_unpublished';--> statement-breakpoint
CREATE TABLE "config_activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "config_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"config_database_id" text NOT NULL,
	"kind" "inlet_config_activity_kind" NOT NULL,
	"actor_user_id" text,
	"actor_credential_id" text,
	"version_number" integer,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "config_activity_one_actor" CHECK (num_nonnulls("config_activity"."actor_user_id", "config_activity"."actor_credential_id") = 1)
);
--> statement-breakpoint
CREATE TABLE "config_database_memberships" (
	"config_database_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role" "inlet_role" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "config_database_memberships_config_database_id_user_id_pk" PRIMARY KEY("config_database_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "config_databases" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"name" text NOT NULL,
	"refresh_interval_minutes" integer NOT NULL,
	"country_derivation" boolean DEFAULT true NOT NULL,
	"active_version_number" integer,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "config_drafts" (
	"config_database_id" text PRIMARY KEY NOT NULL,
	"template" jsonb NOT NULL,
	"revision" integer DEFAULT 0 NOT NULL,
	"updated_by_user_id" text,
	"updated_by_credential_id" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "config_drafts_one_actor" CHECK (num_nonnulls("config_drafts"."updated_by_user_id", "config_drafts"."updated_by_credential_id") = 1)
);
--> statement-breakpoint
CREATE TABLE "config_reach" (
	"config_database_id" text NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"kind" "inlet_config_reach_kind" NOT NULL,
	"subject" text DEFAULT '' NOT NULL,
	"count" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "config_reach_config_database_id_period_start_kind_subject_pk" PRIMARY KEY("config_database_id","period_start","kind","subject")
);
--> statement-breakpoint
CREATE TABLE "config_versions" (
	"config_database_id" text NOT NULL,
	"number" integer NOT NULL,
	"template" jsonb NOT NULL,
	"published_by_user_id" text,
	"published_by_credential_id" text,
	"published_at" timestamp with time zone DEFAULT now() NOT NULL,
	"note" text,
	"draft_revision" integer NOT NULL,
	"change_summary" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"rolled_back_from" integer,
	CONSTRAINT "config_versions_config_database_id_number_pk" PRIMARY KEY("config_database_id","number"),
	CONSTRAINT "config_versions_one_actor" CHECK (num_nonnulls("config_versions"."published_by_user_id", "config_versions"."published_by_credential_id") = 1)
);
--> statement-breakpoint
ALTER TABLE "invitations" ADD COLUMN "config_database_id" text;--> statement-breakpoint
ALTER TABLE "notification_deliveries" ADD COLUMN "config_activity_id" integer;--> statement-breakpoint
ALTER TABLE "config_activity" ADD CONSTRAINT "config_activity_config_database_id_config_databases_id_fk" FOREIGN KEY ("config_database_id") REFERENCES "public"."config_databases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config_database_memberships" ADD CONSTRAINT "config_database_memberships_config_database_id_config_databases_id_fk" FOREIGN KEY ("config_database_id") REFERENCES "public"."config_databases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config_database_memberships" ADD CONSTRAINT "config_database_memberships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config_databases" ADD CONSTRAINT "config_databases_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config_databases" ADD CONSTRAINT "config_databases_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config_drafts" ADD CONSTRAINT "config_drafts_config_database_id_config_databases_id_fk" FOREIGN KEY ("config_database_id") REFERENCES "public"."config_databases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config_reach" ADD CONSTRAINT "config_reach_config_database_id_config_databases_id_fk" FOREIGN KEY ("config_database_id") REFERENCES "public"."config_databases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config_versions" ADD CONSTRAINT "config_versions_config_database_id_config_databases_id_fk" FOREIGN KEY ("config_database_id") REFERENCES "public"."config_databases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "config_activity_db_created_idx" ON "config_activity" USING btree ("config_database_id","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "config_database_memberships_user_idx" ON "config_database_memberships" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "config_databases_project_idx" ON "config_databases" USING btree ("project_id");--> statement-breakpoint
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_config_database_id_config_databases_id_fk" FOREIGN KEY ("config_database_id") REFERENCES "public"."config_databases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_deliveries" ADD CONSTRAINT "notification_deliveries_config_activity_id_config_activity_id_fk" FOREIGN KEY ("config_activity_id") REFERENCES "public"."config_activity"("id") ON DELETE cascade ON UPDATE no action;