import type { RedactionPolicy } from './types.js';

/**
 * CR-094: the default redaction policy.
 *
 * An exception message is the one field in the envelope that routinely carries what a
 * user typed: `Unexpected token in JSON at "…"`, `alice@corp.com is not a valid address`,
 * `/Users/alice/secret.docx could not be opened`. The default keeps a message only when it
 * matches a shape known to be generated by the runtime rather than by data, and replaces
 * everything else with `<redacted>`.
 *
 * The leading token is kept only when it is errno-shaped (`ENOENT:`, `ERR_MODULE_NOT_FOUND`),
 * which is the one case where it carries triage value and cannot carry a payload. Keeping it
 * unconditionally — what this policy did before 0.1.2 — meant a message whose first word was
 * the private part shipped it verbatim behind a marker that read as redacted. Group titles do
 * not depend on it: they come from the exception type and the top in-app frame (CR-051).
 *
 * Integrators who know their messages are safe install `keepMessages`; those who know a few
 * extra safe shapes install `redactExcept`.
 */
const KNOWN_SAFE: RegExp[] = [
  /^Cannot read propert(?:y|ies) of (?:undefined|null)(?: \(reading '[\w$]+'\))?$/,
  /^Cannot set propert(?:y|ies) of (?:undefined|null)(?: \(setting '[\w$]+'\))?$/,
  /^[\w$.]+ is not a function$/,
  /^[\w$.]+ is not defined$/,
  /^[\w$.]+ is not iterable$/,
  /^[\w$.]+ is not a constructor$/,
  /^Cannot access '[\w$]+' before initialization$/,
  /^Assignment to constant variable\.$/,
  /^Maximum call stack size exceeded$/,
  /^Invalid array length$/,
  /^Unexpected end of (?:JSON )?input$/,
  /^Unexpected token '?.?'? in JSON at position \d+$/,
  /^Unexpected token .{1,3}$/,
  /^Failed to fetch$/,
  /^NetworkError when attempting to fetch resource\.$/,
  /^Load failed$/,
  /^The operation was aborted\.?$/,
  /^(?:socket hang up|ECONNREFUSED|ECONNRESET|ETIMEDOUT|EPIPE|ENOTFOUND|EAI_AGAIN|EACCES|EPERM|EMFILE|ENOSPC)\b[^/'"\\]*$/,
  /^(?:Out of memory|Script error\.?)$/,
  /^ResizeObserver loop (?:limit exceeded|completed with undelivered notifications\.)$/,
  /^Unhandled promise rejection$/,
  /^(?:Request|Timeout|Navigation) (?:timed out|aborted)\b.*$/,
];

/**
 * An errno or Node error code: all caps, digits and underscores, optionally followed by the
 * colon Node puts after it. `ENOENT`, `ERR_MODULE_NOT_FOUND`, `EACCES:`. Nothing a user types
 * takes this shape, so keeping it leaks nothing while keeping the message worth reading.
 */
const ERRNO = /^[A-Z][A-Z0-9_]{2,}:?$/;

function redact(trimmed: string): string {
  const first = trimmed.split(/\s+/)[0] ?? '';
  return ERRNO.test(first) ? `${first} <redacted>` : '<redacted>';
}

export const defaultRedaction: RedactionPolicy = (message) => {
  const trimmed = message.trim();
  if (trimmed === '') return '';
  if (KNOWN_SAFE.some((pattern) => pattern.test(trimmed))) return trimmed;
  return redact(trimmed);
};

/** Builds a policy from the integrator's own list of safe shapes; everything else is redacted. */
export function redactExcept(safe: RegExp[]): RedactionPolicy {
  return (message) => {
    const trimmed = message.trim();
    if (trimmed === '') return '';
    if (safe.some((pattern) => pattern.test(trimmed))) return trimmed;
    return redact(trimmed);
  };
}

/**
 * CR-113: sends exception messages verbatim, for integrators who know their messages carry no
 * user data. The deliberate, named way to opt out of CR-094 — `init({ redaction: keepMessages })`
 * greps, an inline `(message) => message` does not.
 */
export const keepMessages: RedactionPolicy = (message) => message;

/**
 * CR-117: an application-oriented policy, for messages your own code writes.
 *
 * `defaultRedaction` allowlists by *shape*, which fits messages the engine generates and is
 * inverted for messages an application authors. Measured over a realistic sample: every
 * engine message survived and every application message became a bare `<redacted>` — the
 * diagnostic half, which usually carries no user data at all. A database of `<redacted>` reads
 * as a broken integration, and that misdiagnosis costs a round to disprove.
 *
 * This redacts by *pattern* instead: the things that actually carry user data are removed and
 * the sentence around them survives. It is not the default, because the default has already
 * changed once and a reporting tool that keeps changing what it reports is worse than one with
 * an awkward default.
 *
 * `'Wallet sync failed after 3 retries'` survives intact;
 * `'/Users/alice/secret.docx could not be opened'` becomes `'<path> could not be opened'`.
 */
const SENSITIVE: [RegExp, string][] = [
  // URLs first: one contains slashes and would otherwise be eaten by the path pattern.
  [/\b[a-z][a-z0-9+.-]*:\/\/\S+/gi, '<url>'],
  [/[\w.+-]+@[\w-]+(?:\.[\w-]+)+/g, '<email>'],
  // An absolute path: at least two segments after a leading separator or drive letter, and it
  // must start at a boundary — otherwise `2026/09/22` and `3/4` match, and a character class
  // containing a space runs straight through the rest of the sentence. The boundary is captured
  // and put back rather than matched with a lookbehind, which would be a parse error in older
  // Safari and this module loads in the browser entry. A path containing spaces is therefore
  // redacted only up to the first one, which still removes the user's name.
  [/(^|[\s(<"'])((?:[A-Za-z]:)?(?:[/\\][\w.~%-]+){2,})/g, '$1<path>'],
  [/\b\d{1,3}(?:\.\d{1,3}){3}\b/g, '<ip>'],
  // Keys, hashes, JWT segments, session ids: long and opaque enough that no prose looks like it.
  [/\b[A-Za-z0-9_-]{24,}\b/g, '<token>'],
];

export const redactPatterns: RedactionPolicy = (message) => {
  const trimmed = message.trim();
  if (trimmed === '') return '';
  return SENSITIVE.reduce((text, [pattern, marker]) => text.replace(pattern, marker), trimmed);
};
