import type { RedactionPolicy } from './types.js';

/**
 * CR-094: the default redaction policy.
 *
 * An exception message is the one field in the envelope that routinely carries what a
 * user typed: `Unexpected token in JSON at "…"`, `ENOENT: no such file '/Users/alice/…'`,
 * `Invalid email "alice@…"`. The default keeps a message only when it matches a shape
 * known to be generated by the runtime rather than by data, and replaces everything else
 * with its first token followed by `<redacted>`, so the group still has a title
 * ("TypeError · Cannot <redacted>") without the payload.
 *
 * Integrators who know their messages are safe install `(message) => message`.
 */
const KNOWN_SAFE: RegExp[] = [
  /^Cannot read propert(?:y|ies) of (?:undefined|null)(?: \(reading '[\w$]+'\))?$/,
  /^Cannot set propert(?:y|ies) of (?:undefined|null)(?: \(setting '[\w$]+'\))?$/,
  /^[\w$.]+ is not a function$/,
  /^[\w$.]+ is not defined$/,
  /^[\w$.]+ is not iterable$/,
  /^[\w$.]+ is not a constructor$/,
  /^Cannot access '[\w$]+' before initialization$/,
  /^Assignment to constant variable\.$/,
  /^Maximum call stack size exceeded$/,
  /^Invalid array length$/,
  /^Unexpected end of (?:JSON )?input$/,
  /^Unexpected token '?.?'? in JSON at position \d+$/,
  /^Unexpected token .{1,3}$/,
  /^Failed to fetch$/,
  /^NetworkError when attempting to fetch resource\.$/,
  /^Load failed$/,
  /^The operation was aborted\.?$/,
  /^(?:socket hang up|ECONNREFUSED|ECONNRESET|ETIMEDOUT|EPIPE|ENOTFOUND|EAI_AGAIN|EACCES|EPERM|EMFILE|ENOSPC)\b[^/'"\\]*$/,
  /^(?:Out of memory|Script error\.?)$/,
  /^ResizeObserver loop (?:limit exceeded|completed with undelivered notifications\.)$/,
  /^Unhandled promise rejection$/,
  /^(?:Request|Timeout|Navigation) (?:timed out|aborted)\b.*$/,
];

export const defaultRedaction: RedactionPolicy = (message) => {
  const trimmed = message.trim();
  if (trimmed === '') return '';
  if (KNOWN_SAFE.some((pattern) => pattern.test(trimmed))) return trimmed;
  const first = trimmed.split(/\s+/)[0] ?? '';
  return `${first} <redacted>`;
};

/** Builds a policy from the integrator's own list of safe shapes; everything else is redacted. */
export function redactExcept(safe: RegExp[]): RedactionPolicy {
  return (message) => {
    const trimmed = message.trim();
    if (safe.some((pattern) => pattern.test(trimmed))) return trimmed;
    const first = trimmed.split(/\s+/)[0] ?? '';
    return trimmed === '' ? '' : `${first} <redacted>`;
  };
}
