import type { RedactionPolicy } from './types.js';

/**
 * CR-094: the default redaction policy.
 *
 * An exception message is the one field in the envelope that routinely carries what a
 * user typed: `Unexpected token in JSON at "…"`, `alice@corp.com is not a valid address`,
 * `/Users/alice/secret.docx could not be opened`. The default keeps a message only when it
 * matches a shape known to be generated by the runtime rather than by data, and replaces
 * everything else with `<redacted>`.
 *
 * The leading token is kept only when it is errno-shaped (`ENOENT:`, `ERR_MODULE_NOT_FOUND`),
 * which is the one case where it carries triage value and cannot carry a payload. Keeping it
 * unconditionally — what this policy did before 0.1.2 — meant a message whose first word was
 * the private part shipped it verbatim behind a marker that read as redacted. Group titles do
 * not depend on it: they come from the exception type and the top in-app frame (CR-051).
 *
 * Integrators who know their messages are safe install `keepMessages`; those who know a few
 * extra safe shapes install `redactExcept`.
 */
const KNOWN_SAFE: RegExp[] = [
  /^Cannot read propert(?:y|ies) of (?:undefined|null)(?: \(reading '[\w$]+'\))?$/,
  /^Cannot set propert(?:y|ies) of (?:undefined|null)(?: \(setting '[\w$]+'\))?$/,
  /^[\w$.]+ is not a function$/,
  /^[\w$.]+ is not defined$/,
  /^[\w$.]+ is not iterable$/,
  /^[\w$.]+ is not a constructor$/,
  /^Cannot access '[\w$]+' before initialization$/,
  /^Assignment to constant variable\.$/,
  /^Maximum call stack size exceeded$/,
  /^Invalid array length$/,
  /^Unexpected end of (?:JSON )?input$/,
  /^Unexpected token '?.?'? in JSON at position \d+$/,
  /^Unexpected token .{1,3}$/,
  /^Failed to fetch$/,
  /^NetworkError when attempting to fetch resource\.$/,
  /^Load failed$/,
  /^The operation was aborted\.?$/,
  /^(?:socket hang up|ECONNREFUSED|ECONNRESET|ETIMEDOUT|EPIPE|ENOTFOUND|EAI_AGAIN|EACCES|EPERM|EMFILE|ENOSPC)\b[^/'"\\]*$/,
  /^(?:Out of memory|Script error\.?)$/,
  /^ResizeObserver loop (?:limit exceeded|completed with undelivered notifications\.)$/,
  /^Unhandled promise rejection$/,
  /^(?:Request|Timeout|Navigation) (?:timed out|aborted)\b.*$/,
];

/**
 * An errno or Node error code: all caps, digits and underscores, optionally followed by the
 * colon Node puts after it. `ENOENT`, `ERR_MODULE_NOT_FOUND`, `EACCES:`. Nothing a user types
 * takes this shape, so keeping it leaks nothing while keeping the message worth reading.
 */
const ERRNO = /^[A-Z][A-Z0-9_]{2,}:?$/;

function redact(trimmed: string): string {
  const first = trimmed.split(/\s+/)[0] ?? '';
  return ERRNO.test(first) ? `${first} <redacted>` : '<redacted>';
}

export const defaultRedaction: RedactionPolicy = (message) => {
  const trimmed = message.trim();
  if (trimmed === '') return '';
  if (KNOWN_SAFE.some((pattern) => pattern.test(trimmed))) return trimmed;
  return redact(trimmed);
};

/** Builds a policy from the integrator's own list of safe shapes; everything else is redacted. */
export function redactExcept(safe: RegExp[]): RedactionPolicy {
  return (message) => {
    const trimmed = message.trim();
    if (trimmed === '') return '';
    if (safe.some((pattern) => pattern.test(trimmed))) return trimmed;
    return redact(trimmed);
  };
}

/**
 * CR-113: sends exception messages verbatim, for integrators who know their messages carry no
 * user data. The deliberate, named way to opt out of CR-094 — `init({ redaction: keepMessages })`
 * greps, an inline `(message) => message` does not.
 */
export const keepMessages: RedactionPolicy = (message) => message;
