import { LIMITS } from '@inlet/shared';

/**
 * The OpenAPI document's static half. Paths and schemas are generated from the Zod
 * route schemas by @fastify/swagger, so only the descriptive parts live here.
 */
export function openapiDocument(publicUrl: string) {
  return {
    openapi: '3.1.0',
    info: {
      title: 'Inlet API',
      version: '1.0.0',
      summary: 'The self-hosted feedback collector.',
      description: [
        'Inlet separates form definition from form rendering and response storage. Your',
        'application fetches a published form definition, renders it however it likes, and',
        'posts the answers back in one call.',
        '',
        '## Collecting feedback in four calls',
        '',
        '```bash',
        'BASE=' + publicUrl,
        'KEY=ipk_your_publishable_client_key',
        'DB=fdb_your_feedback_database_id',
        '',
        '# 1. Read the published form',
        'curl -s "$BASE/v1/feedback-databases/$DB/form" -H "Authorization: Bearer $KEY"',
        '',
        '# 2. Open a submission intent',
        'curl -s -X POST "$BASE/v1/feedback-databases/$DB/submission-intents" \\',
        '  -H "Authorization: Bearer $KEY"',
        '',
        '# 3. Optionally attach a screenshot',
        'curl -s -X POST "$BASE/v1/feedback-databases/$DB/submission-intents/$INTENT/attachments" \\',
        '  -H "Authorization: Bearer $KEY" -H "X-Inlet-Intent-Token: $TOKEN" \\',
        '  -F questionId=el_xxxxxxxxxxxx -F file=@screenshot.png',
        '',
        '# 4. Submit everything at once',
        'curl -s -X POST "$BASE/v1/feedback-databases/$DB/submission-intents/$INTENT/submit" \\',
        '  -H "Authorization: Bearer $KEY" -H "X-Inlet-Intent-Token: $TOKEN" \\',
        '  -H \'content-type: application/json\' \\',
        '  -d \'{"formVersion":1,"answers":{"el_xxxxxxxxxxxx":{"value":"It works"}}}\'',
        '```',
        '',
        '## Two kinds of key',
        '',
        'A **publishable client key** (`ipk_…`) is safe to embed in a browser or mobile',
        'app. It authorizes only the four calls above.',
        '',
        'A **secret server key** (`isk_…`) carries project Admin authority: it can read',
        'and export submissions, manage forms, and delete data within its own project.',
        'Keep it on a server. It is shown once, when you create it.',
        '',
        'Send either as `Authorization: Bearer <key>`. The management interface uses a',
        'session cookie instead, obtained from `POST /v1/auth/sign-in`.',
        '',
        '## Answers',
        '',
        'Answers are keyed by stable question ID. The shape follows the question type in',
        'the pinned form version, so you never repeat the type:',
        '',
        '| Question type | Answer |',
        '| --- | --- |',
        '| single-select choice | `{"optionId": "op_…"}` |',
        '| multi-select choice | `{"optionIds": ["op_…", "op_…"]}` |',
        '| single- or multi-line text | `{"value": "…"}` |',
        '| email | `{"value": "someone@example.com"}` |',
        '| screenshot upload | `{"attachmentIds": ["att_…"]}` |',
        '',
        'Omit a question entirely to leave an optional question unanswered. An empty',
        'string never satisfies a required question.',
        '',
        '## Retrying safely',
        '',
        'Every submission starts with a server-issued intent, which makes retries safe.',
        'Repeating a finalization with the same payload returns the original result;',
        'repeating it with a different payload is a conflict and stores nothing; and a',
        'validation failure leaves the intent usable so you can correct and resend.',
        '',
        '## Limits',
        '',
        `- \`clientContext\`: ${LIMITS.clientContextMaxBytes} bytes serialized as UTF-8.`,
        `- Screenshots: JPEG, PNG or WebP, ${Math.floor(LIMITS.imageMaxSourceBytes / (1024 * 1024))} MB and ${LIMITS.attachmentMaxPixels / 1_000_000} megapixels per file, ${LIMITS.submissionMaxAttachments} per submission, ${LIMITS.intentMaxUploads} uploads per intent. Animated images are rejected.`,
        `- Every accepted image is re-encoded to WebP and brought inside ${Math.floor(LIMITS.imageMaxStoredBytes / (1024 * 1024))} MB of storage, giving up quality before pixels. The width, height and bytes in an upload response describe what was stored, which may be smaller than what was sent.`,
        '- Security rate limits apply to sign-in, intent creation, uploads and',
        '  finalization. They are not configurable.',
        '',
        '## Errors',
        '',
        'Every failure returns `{"error":{"code","message","details?"}}`. The `code` is',
        'stable and safe to branch on; `details` carries `questionId` for answer problems',
        'and `path` for request-shape problems.',
      ].join('\n'),
      license: { name: 'MIT' },
    },
    servers: [{ url: publicUrl, description: 'This deployment' }],
    tags: [
      { name: 'Client feedback flow', description: 'What your application calls to collect feedback.' },
      { name: 'Authentication', description: 'Management sessions.' },
      { name: 'Projects', description: 'Top-level containers.' },
      { name: 'Feedback databases', description: 'One logical form and its responses.' },
      { name: 'Form builder', description: 'Drafts and published versions.' },
      { name: 'Credentials', description: 'Publishable client keys and secret server keys.' },
      { name: 'Submissions', description: 'Reviewing, exporting and deleting feedback.' },
    ],
    components: {
      securitySchemes: {
        projectKey: {
          type: 'http' as const,
          scheme: 'bearer',
          description:
            'A project credential: a publishable client key (`ipk_…`) for the feedback flow, or a secret server key (`isk_…`) for everything in its project.',
        },
        session: {
          type: 'apiKey' as const,
          in: 'cookie' as const,
          name: 'inlet_session',
          description: 'The management session cookie set by POST /v1/auth/sign-in.',
        },
      },
    },
    security: [{ session: [] as string[] }, { projectKey: [] as string[] }] as Record<string, string[]>[],
  };
}
